import type { BusinessStatus, BusinessType } from "@/lib/business";

export type SeedBusinessInput = {
  id: string;
  name: string;
  type: BusinessType;
  address?: string;
  city?: string;
  phone?: string;
  website?: string;
  instagram?: string;
  tags: string[];
  note?: string;
  status: BusinessStatus;
};

export const SEED_BUSINESSES: SeedBusinessInput[] = [
  {
    id: "nails-by-kim-studio",
    name: "Nails by Kim Studio",
    type: "nails",
    address: "2315 S Campbell Ave, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 887-8303",
    website: "https://nailsbykimstudio.com/",
    tags: ["nails", "springfield", "target", "no-booking"],
    note: "Site promotes call + walk-ins; no online booking widget found",
    status: "target",
  },
  {
    id: "divine-nail-lounge",
    name: "Divine Nail Lounge & Spa",
    type: "nails",
    address: "1500 E Sunshine St, Springfield, MO 65804",
    city: "Springfield",
    phone: "(417) 306-9798",
    website: "https://www.divinenailloungespa.com/",
    tags: ["nails", "spa", "springfield", "target", "no-booking"],
    note: "Homepage CALL TO BOOK; phone CTA only",
    status: "target",
  },
  {
    id: "top-nails",
    name: "Top Nails",
    type: "nails",
    address: "457 Aldersgate Dr, Nixa, MO 65714",
    city: "Nixa",
    phone: "(417) 725-0082",
    website: "https://topnailsnixa.com/",
    instagram: "topnails_nixa",
    tags: ["nails", "nixa", "target", "no-booking"],
    status: "target",
  },
  {
    id: "nixa-nails",
    name: "Nixa Nails",
    type: "nails",
    address: "692 W Mt Vernon St, Nixa, MO 65714",
    city: "Nixa",
    phone: "(417) 596-4402",
    website: "https://nixanailsmo.com/",
    instagram: "nixa_nails_mo",
    tags: ["nails", "nixa", "target", "no-booking"],
    status: "target",
  },
  {
    id: "pink-white-nail-studio",
    name: "Pink + White Nail Studio",
    type: "nails",
    address: "900 E Battlefield Rd Ste 148, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 319-5757",
    instagram: "pwnailstudio",
    tags: ["nails", "springfield", "target", "no-booking"],
    note: "Call for day-of / message for consults; no booking site",
    status: "target",
  },
  {
    id: "gloss-nail-lounge",
    name: "Gloss Nail Lounge",
    type: "nails",
    address: "2712 S Glenstone Ave, Springfield, MO 65804",
    city: "Springfield",
    phone: "(417) 350-1048",
    instagram: "gloss417",
    tags: ["nails", "springfield", "target", "no-booking"],
    status: "target",
  },
  {
    id: "gloss-and-go-nail-bar",
    name: "Gloss & Go Nail Bar",
    type: "nails",
    address: "3121 S Campbell Ave, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 771-5330",
    website: "https://glossngonailbar.com/",
    tags: ["nails", "springfield", "target", "no-booking"],
    note: "Appt & walk-ins welcome; phone CTA",
    status: "target",
  },
  {
    id: "lucky-nails",
    name: "Lucky Nails",
    type: "nails",
    address: "640 W Republic Rd Ste 120, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 823-8829",
    website: "http://luckynailsspringfieldmo.com/",
    tags: ["nails", "springfield", "target", "no-booking"],
    status: "target",
  },
  {
    id: "le-posh-nail-studio",
    name: "Le Posh Nail Studio",
    type: "nails",
    address: "3433 S Campbell Ave, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 771-5233",
    website: "https://leposhnailstudio.com/",
    tags: ["nails", "springfield", "target", "no-booking"],
    status: "target",
  },
  {
    id: "aqua-nails-spa",
    name: "Aqua Nails Spa",
    type: "nails",
    address:
      "3630 S Campbell Ave (Kickapoo) + 2825 S Glenstone Ave Battlefield Mall, Springfield",
    city: "Springfield",
    phone: "(417) 501-8179",
    website: "https://aquanailsspaspringfield.com/",
    tags: ["nails", "springfield", "target", "no-booking"],
    status: "target",
  },
  {
    id: "stylin-nails-spa",
    name: "Stylin' Nails & Spa",
    type: "nails",
    address: "2775 S Campbell Ave Ste 105, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 771-5458",
    tags: ["nails", "springfield", "target", "no-booking"],
    note: "No website; FB: stylinnails.spa",
    status: "target",
  },
  {
    id: "trende-nail-spa",
    name: "Trendē Nail Spa",
    type: "nails",
    address: "762 US-60, Republic, MO 65738",
    city: "Republic",
    phone: "(417) 732-2808",
    website: "https://trendenailsparepublic.com/",
    tags: ["nails", "republic", "target", "no-booking"],
    note: "Walk-ins + text for quotes",
    status: "target",
  },
  {
    id: "us-nails",
    name: "US Nails",
    type: "nails",
    address: "1331 S Glenstone Ave, Springfield, MO 65804",
    city: "Springfield",
    phone: "(417) 881-8838",
    tags: ["nails", "springfield", "target", "no-booking"],
    note: "No usable website",
    status: "target",
  },
  {
    id: "studio-8-hair-co",
    name: "Studio 8 Hair Co.",
    type: "hair",
    address: "115 N Massey Blvd, Nixa, MO 65714",
    city: "Nixa",
    phone: "(417) 374-7660",
    tags: ["hair", "nixa", "target", "no-booking"],
    note: "Not taking online bookings — call or stop by",
    status: "target",
  },
  {
    id: "envy-salon",
    name: "Envy Salon",
    type: "hair",
    address: "320 N Massey Blvd, Nixa, MO 65714",
    city: "Nixa",
    phone: "(417) 725-0050",
    tags: ["hair", "nails", "nixa", "target", "no-booking"],
    note: "Fresha venue page is Call to book",
    status: "target",
  },
  {
    id: "hair-revue",
    name: "Hair Revue",
    type: "hair",
    address: "208 N Main St, Nixa, MO 65714",
    city: "Nixa",
    phone: "(417) 725-2677",
    tags: ["hair", "nixa", "target", "no-booking"],
    status: "target",
  },
  {
    id: "salon-316",
    name: "Salon 3:16",
    type: "hair",
    address: "505 N 21st St, Ozark, MO 65721",
    city: "Ozark",
    phone: "(417) 581-2316",
    website: "https://www.salon316ozark.com/",
    tags: ["hair", "barber", "ozark", "target", "no-booking"],
    note: "Cannot make appointments through website — call only",
    status: "target",
  },
  {
    id: "talk-of-the-town-barbershop",
    name: "Talk of the Town Barbershop",
    type: "barber",
    address: "1303 S Glenstone Ave, Springfield, MO 65804",
    city: "Springfield",
    phone: "(417) 631-6229",
    website: "https://www.talkofthetownbarbershop.com/",
    instagram: "talkofthetownbarbers",
    tags: ["barber", "springfield", "target", "no-booking"],
    status: "target",
  },
  {
    id: "springfield-barbershop",
    name: "Springfield Barbershop",
    type: "barber",
    address: "3170 E Sunshine St Suite G, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 522-3554",
    website: "http://www.springfieldbarbershop417.com/",
    tags: ["barber", "springfield", "target", "no-booking"],
    status: "target",
  },
  {
    id: "walnut-street-barber-shop",
    name: "Walnut Street Barber Shop",
    type: "barber",
    address: "205 E Walnut St, Springfield, MO 65806",
    city: "Springfield",
    phone: "(417) 831-3570",
    website: "http://walnutstreetbarber.com/",
    instagram: "walnutstreetbarbershop",
    tags: ["barber", "springfield", "target", "no-booking"],
    note: "Walk-Ins Only",
    status: "target",
  },
  {
    id: "glam-boutique-nails",
    name: "Glam Boutique Nails and Spa",
    type: "nails",
    address: "2150 W Republic Rd #116, Springfield, MO 65807",
    city: "Springfield",
    phone: "(417) 771-5675",
    instagram: "glamboutique_nailsandspa",
    tags: ["nails", "springfield", "hold"],
    note: "Some listings claim GoCheckIn; verify no book button before pitch",
    status: "hold",
  },
  {
    id: "reflections-barbershop",
    name: "Reflections Barbershop LLC",
    type: "barber",
    address: "address conflict",
    city: "Springfield",
    phone: "(417) 771-5427 confirm",
    tags: ["barber", "springfield", "hold"],
    note: "Confirm address + booking",
    status: "hold",
  },
  {
    id: "bos-barbershop",
    name: "Bo's Barbershop",
    type: "barber",
    address: "~2346 W Division St, Springfield 65802",
    city: "Springfield",
    tags: ["barber", "springfield", "hold"],
    note: "Confirm phone + booking",
    status: "hold",
  },
];
