import { addDaysISO, startOfWeek, todayISO } from "@/lib/dates";
import type { ChecklistItem, UpsertCardInput } from "@/lib/schema";

export const SEED_CARDS: UpsertCardInput[] = [
  {
    id: "eng-staging-pr-42",
    title: "Review staging PR #42",
    owner: "eng",
    cadence: "once",
    status: "ready",
    needsJoseph: true,
    nextStep: "Pull joseph-pick and review diff",
    tags: ["joseph-pick", "pr"],
  },
  {
    id: "eng-qa-fail-checkout",
    title: "QA fail: checkout edge case",
    owner: "eng",
    cadence: "daily",
    status: "blocked",
    needsJoseph: true,
    nextStep: "Unblock BEA / re-run QA after fix",
    tags: ["qa", "bea"],
  },
  {
    id: "eng-bea-blocker",
    title: "BEA env access blocker",
    owner: "eng",
    cadence: "once",
    status: "blocked",
    needsJoseph: true,
    nextStep: "Restore BEA credentials for CI",
    tags: ["bea"],
  },
  {
    id: "mkt-sunday-packet",
    title: "Sunday marketing packet",
    owner: "marketing",
    cadence: "weekly",
    status: "open",
    needsJoseph: false,
    nextStep: "Assemble drafts for Joseph review Sunday",
    tags: ["packet"],
  },
  {
    id: "mkt-weekday-drafts",
    title: "Weekday content drafts",
    owner: "marketing",
    cadence: "daily",
    status: "open",
    needsJoseph: false,
    nextStep: "Agents draft; queue for Joseph only if posting",
  },
  {
    id: "mkt-saturday-engage",
    title: "Saturday engage + Canva yes",
    owner: "marketing",
    cadence: "weekly",
    status: "ready",
    needsJoseph: true,
    nextStep: "Joseph approve post + Canva only",
    tags: ["canva", "post"],
  },
  {
    id: "sales-beta-trial",
    title: "BETA trial: get-started",
    owner: "sales",
    cadence: "once",
    status: "ready",
    needsJoseph: true,
    nextStep: "Share viselle.net/get-started code BETA",
    link: "https://viselle.net/get-started",
    dueDate: "2026-10-31",
    tags: ["BETA", "trial"],
  },
  {
    id: "sales-15min-setup",
    title: "15-min setup call",
    owner: "sales",
    cadence: "weekly",
    status: "ready",
    needsJoseph: true,
    nextStep: "Joseph join / approve setup call",
    tags: ["setup"],
  },
  {
    id: "sales-mixer-followup",
    title: "Mixer follow-up DM/email",
    owner: "sales",
    cadence: "weekly",
    status: "open",
    needsJoseph: true,
    nextStep: "Approve follow-up DM/email copy",
    tags: ["mixer"],
  },
  {
    id: "sales-chamber-prep",
    title: "Chamber prep",
    owner: "sales",
    cadence: "monthly",
    status: "open",
    needsJoseph: false,
    nextStep: "Prep materials before Chamber event",
    tags: ["chamber"],
  },
  {
    id: "sup-ship-date-yes",
    title: "Ship-date / major-feature yes",
    owner: "support",
    cadence: "once",
    status: "ready",
    needsJoseph: true,
    nextStep: "Joseph yes on ship date or major feature",
    tags: ["ship", "major"],
  },
  {
    id: "books-stripe-pktest",
    title: "Stripe login / pk_test / failed charge",
    owner: "books",
    cadence: "daily",
    status: "blocked",
    needsJoseph: true,
    nextStep: "Joseph Stripe login; inspect failed charge + invoice gap",
    tags: ["stripe", "pk_test", "cash"],
  },
];

export function buildSeedChecklist(today = todayISO()): Omit<
  ChecklistItem,
  "createdAt" | "updatedAt"
>[] {
  const monday = startOfWeek(today);
  return [
    {
      id: "coo-today-needs",
      title: "Clear Needs Joseph blockers before noon",
      done: false,
      plannedDate: today,
      sortOrder: 0,
    },
    {
      id: "coo-today-stripe",
      title: "Joseph Stripe login — failed charge + invoice gap",
      done: false,
      plannedDate: today,
      sortOrder: 1,
    },
    {
      id: "coo-mon-packet",
      title: "Confirm Sunday marketing packet is queued",
      done: false,
      plannedDate: monday,
      sortOrder: 0,
    },
    {
      id: "coo-wed-mixer",
      title: "Prep mixer follow-up copy for Joseph yes",
      done: false,
      plannedDate: addDaysISO(monday, 2),
      sortOrder: 0,
    },
    {
      id: "coo-fri-chamber",
      title: "Chamber materials draft (no Joseph needed)",
      done: false,
      plannedDate: addDaysISO(monday, 4),
      sortOrder: 0,
    },
  ];
}

